Properly use infinite timeout for threading.Event
None seems to be the proper way of setting an infinite timeout for the
threading.Event objects. float("inf") apparently worked on Python 2 but does
not work on Python 3 and raises:
OverflowError: timestamp too large to convert to C _PyTime_t
Change all timeouts from float("inf") to None.